Deploy GB feature branch in new cluster
Ensembl/ensembl-dauphin-style-compiler pull request #106
Opened 2024-03-13 02:43 UTC by veidenberg

Adds review job in GitLab CI/CD pipeline in order to deploy Genome Browser non-default backend (feature branch) to review app namespace in the new dev cluster.
Example deployment: http://deploy-review-nkhdev.review.ensembl.org/api/browser/data/hi

2024-03-13 09:00 UTC, kamaldodiya requested changes

2024-03-13 09:00 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +  extends: .deploy_backend_review
There is no point of running same steps time and again i.e creating svc,ing,cm etc. That is required only once. 
There should be two separate Jobs

1. Setup a review app - create cm,secret, svc ,ing etc ( Runs only once at the time of creation of branch)
2. Deployment ( updating latest build in that branch) to a particular namespace - Run on every commit to a specific branch

2024-03-13 09:00 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +  extends: .deploy_backend_review
Please follow the PR template we have in web-metadata-api.

2024-03-14 09:00 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +    - kubectl -n ensembl-dev create namespace ${CI_COMMIT_REF_SLUG} || true
`-n ensembl-dev` is not needed while creating namespace

2024-03-14 09:02 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +    - kubectl apply -f genome-browser/memcached/service.yaml
Best is to use the `memcached` in the `ensembl-dev` namespace. Just use the different key for storing data.

2024-03-14 09:11 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +  - setup
This should be the first step. It will execute the job when the new branch is created but otherwise it will be skipped and proceed with rest of the pipeline.

2024-03-14 09:12 UTC, kamaldodiya requested changes
Please see the comments

2024-03-14 13:01 UTC, veidenberg commented on backend-server/.backend-server-ci.yml
> +  - setup
That's how it works currently (sets up k8s when branch is created, but skipped later, then continues with the rest of the pipeline: deployment). I've put it as step 3 to check for code issues (building steps) on new branch before setting up k8s but it might not be a good idea. Moving back as step 1 (always creates k8s setup).

2024-03-14 13:06 UTC, veidenberg commented on backend-server/.backend-server-ci.yml
> +      namespace: ${CI_COMMIT_REF_SLUG}
It does exist by the time the job gets to `script` stage. Should I instead remove this line and specify `-n ${CI_COMMIT_REF_SLUG}` in the kubectl commands in the script?

2024-03-14 14:02 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +  - setup
Well, Mostly the branch will be created from the master branch which I think assumed to be bug free :)

2024-03-14 14:07 UTC, kamaldodiya requested changes

2024-03-14 14:07 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +      namespace: ${CI_COMMIT_REF_SLUG}
Looking at the script it looks like it's appropriate to have it here otherwise it needs to be mentioned everywhere in the script. But it needs to be ensured that this works existing/non-existing namespace.

2024-03-14 15:07 UTC, veidenberg commented on backend-server/.backend-server-ci.yml
> +      namespace: ${CI_COMMIT_REF_SLUG}
It does.

2024-03-14 15:11 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +  - setup
> (you can even delete a branch at any point in gitlab and re-push it from local coimputer and it's treated as new branch, that's how I have tested the setup step without creating new branches)

Did you also delete the namespace and all its resources as well from k8s. The pipeline will show its successful but it is worth ensuring that it created all the resources in k8s in a respective namespace. That is the real test and that is why I had insisted create a branch from `deploy-review-nkhdev` and check that indeed works.

2024-03-14 19:52 UTC, veidenberg commented on backend-server/.backend-server-ci.yml
> +  - setup
No worries, I've tested all combinations I can think of (same/new branch, manual partial/full deletion etc.). The latest commit have been deployed to `deploy-review-nkhdev` (existing ns) and `test-new-branch` (new ns)

2024-03-16 12:38 UTC, veidenberg commented on backend-server/.backend-server-ci.yml
> +  - setup
Ensembl-client now sets up review namespace and pull-secret for backends. GB review pipeline fails at the first step if ns is missing (tested). I removed `deploy-review-nkhdev` ns and branches, deployed  review from scratch. Review app works.

2024-03-18 09:13 UTC, kamaldodiya commented
Setup is still failing https://gitlab.ebi.ac.uk/ensembl-web/ensembl-dauphin-style-compiler/-/jobs/1606360

2024-03-18 09:42 UTC, veidenberg commented
> Setup is still failing https://gitlab.ebi.ac.uk/ensembl-web/ensembl-dauphin-style-compiler/-/jobs/1606360

That is expected and the "did not find namespace" error is there on purpose: you need to create the review namespace with ensembl-client branch before branching any backend (in this case gb). That's because I set up pull-secret with ensembl-client and then don't have to do this for all the backend pipelines (see my previous comments).

2024-03-18 13:06 UTC, kamaldodiya commented
kubectl get ns | grep -q "^${CI_COMMIT_REF_SLUG}" || kubectl create ns ${CI_COMMIT_REF_SLUG}

2024-03-18 13:34 UTC, veidenberg commented
> ```
> kubectl get ns | grep -q "^${CI_COMMIT_REF_SLUG}" || kubectl create ns ${CI_COMMIT_REF_SLUG} 
> ```
> 
> This will take care of the namespace creation across the repos so don't need to have depenedency on some other repo to create ns. I think this is much cleaner approach than || true

I'd prefer not to create review ns in backend, because we also need to add image-pull-secrets and the corresponding gitlab variables. And we would need gitlab-client branching anyway for the review app to function.

2024-03-18 13:48 UTC, kamaldodiya commented on backend-server/.backend-server-ci.yml
> +    - sed -i "s#<CM_PREFIX>#${CI_COMMIT_REF_SLUG}#g" genome-browser/review/secrets.yaml
<MC_PREFIX>

https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests/-/blob/k8s123-migration-gb/genome-browser/review/secrets.yaml#L9

2024-03-18 13:52 UTC, veidenberg commented on backend-server/.backend-server-ci.yml
> +    - sed -i "s#<CM_PREFIX>#${CI_COMMIT_REF_SLUG}#g" genome-browser/review/secrets.yaml
Fixed

2024-03-18 15:27 UTC, kamaldodiya approved these changes

2024-03-18 15:30 UTC, merged