Metadata checksums
Ensembl/ensembl-dauphin-style-compiler pull request #110
Opened 2024-03-22 13:10 UTC by Mehrnaz-Charkhchi

### Description
Look up the sequence hash for a top-level region using web metadata REST API service rather than relying on the chrom_hashes file

### Related JIRA Issue(s)
[ENSWBSITES-2082](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2082)

### Review App URL(s) 
http://metadata-checksums.review.ensembl.org

### Knowledge Base
-

### Example(s)
Genome browser

### Data Availability

### Checklist

- [ ] Black formatting
- [ ] Tests

### Dependencies 
-

2024-03-22 13:42 UTC, kamaldodiya requested changes

2024-03-22 13:42 UTC, kamaldodiya commented on backend-server/config/sources-ebi-dev.toml
> +metadata_url = "http://metadata-api-svc:8014/api/metadata/"
This should be `metadata-api-svc.ensembl-dev` like refget URL.
this config toml will be used by non master branches and will be deployed in its own namespace which just deploys genome-browser backend.
For metadata it has to use service in ensembl-dev namespace.

2024-03-22 14:35 UTC, azangru commented on backend-server/app/model/datalocator.py
> +class MetadataAccessMethod(AccessMethod):
I am confused about names. Why do we call this class `MetadataAccessMethod`? What is an access method?

2024-03-22 16:20 UTC, Mehrnaz-Charkhchi commented on backend-server/app/model/datalocator.py
> +class MetadataAccessMethod(AccessMethod):
Access methods are classes that organise access to different services like file, s3, refget, metadata and any other service we decide to add in the future. 
It's a class because it inherits from AccessMethod and it's how the code and it's how the code was designed in the first place so I can pass the configs and access different methods like get() if we need to.

2024-03-22 16:33 UTC, kamaldodiya approved these changes

2024-03-25 10:05 UTC, veidenberg requested changes
The review app has not been deployed. To fix:
1. Branch and push `medata_checksums` branch in [ensembl-client](https://github.com/Ensembl/ensembl-client)
2. Rebase local `medata_checksums` genome browser branch to `master` and force-push `medata_checksums`
3. In GitLab, [remove](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-dauphin-style-compiler/-/branches) the `medata_checksums` branch and click the `Update Now` button

2024-04-02 10:28 UTC, Mehrnaz-Charkhchi commented
> The review app has not been deployed. To fix:
> 
> 1. Branch and push `medata_checksums` branch in [ensembl-client](https://github.com/Ensembl/ensembl-client)
> 2. Rebase local `medata_checksums` genome browser branch to `master` and force-push `medata_checksums`
> 3. In GitLab, [remove](https://gitlab.ebi.ac.uk/ensembl-web/ensembl-dauphin-style-compiler/-/branches) the `medata_checksums` branch and click the `Update Now` button

@veidenberg  the pipeline failed.

2024-04-02 14:54 UTC, veidenberg commented
[Review app](http://metadata-checksums.review.ensembl.org) is now deployed, but genome browser is not happy. Need to check GB server logs in k8s.

2024-04-04 11:51 UTC, veidenberg approved these changes
GB works as expected in [review app](http://metadata-checksums.review.ensembl.org/genome-browser/grch38?focus=gene:ENSG00000221914). Looks good to me.

2024-04-05 16:27 UTC, merged