Split repeats track
Ensembl/ensembl-dauphin-style-compiler pull request #115
Opened 2024-04-29 08:33 UTC by veidenberg

### Description
* Split repeats track to individual tracks

### Related JIRA Issue(s)
[ENSWBSITES-2500](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2500)

### Review App URL(s) 
http://split-repeats.review.ensembl.org

2024-07-05 08:16 UTC, azangru approved these changes

2024-07-05 09:15 UTC, kamaldodiya requested changes
update staging-2020 to dev-2020

2024-07-08 08:22 UTC, veidenberg commented on backend-server/config/sources-s3.toml
> +metadata_url = "https://staging-2020.ensembl.org/api/metadata/"
Updated

2024-07-08 09:44 UTC, kamaldodiya approved these changes

2024-07-10 16:14 UTC, merged